# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Attachments migrated from Bugzilla for Apache JMeter"
  homepage: https://jmeter.apache.org/

  enabled_merge_buttons:
    squash: true
    merge:  false
    rebase: true

  features:
    wiki: false
    issues: false
    projects: false

  dependabot_alerts:  false
  dependabot_updates: false

  ghp_branch:  gh-pages

notifications:
  commits:      commits@jmeter.apache.org
  issues:       dev@jmeter.apache.org
  pullrequests: dev@jmeter.apache.org
  jira_options: link label
