<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:ns0="http://www.CICSPGM.DSUPFREQ.Request.com" targetNamespace="http://www.CICSPGM.DSUPFREQ.Request.com">
<wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:schema>
<xsd:import schemaLocation="DSUProfileService.xsd2.xsd" namespace="http://www.CICSPGM.DSUPFREQ.Request.com"/></xsd:schema></wsdl:types>
<wsdl:message name="CICSPGMOperationRequest">
<wsdl:part name="parameters" element="xsns:CICSPGMOperation" xmlns:xsns="http://www.CICSPGM.DSUPFREQ.Request.com"/>
<wsdl:part name="request_header" element="xsns:CICSHeader" xmlns:xsns="http://www.CICSPGM.DSUPFREQ.Request.com"/></wsdl:message>
<wsdl:message name="COBCICSOperationResponse">
<wsdl:part name="parameters" element="xsns:COBCICSOperationResponse" xmlns:xsns="http://www.CICSPGM.DSUPFREQ.Request.com"/></wsdl:message>
<wsdl:portType name="DSUProfile">
<wsdl:operation name="getDSUProfile">
<wsdl:input name="CICSPGMOperationRequest" message="ns0:CICSPGMOperationRequest"/>
<wsdl:output name="getDSUProfileResponse" message="ns0:COBCICSOperationResponse"/></wsdl:operation></wsdl:portType>
<wsdl:binding name="DSUProfilePortBinding" type="ns0:DSUProfile">
<soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<wsdl:operation name="getDSUProfile">
<soap11:operation soapAction="" style="document"/>
<wsdl:input name="CICSPGMOperationRequest">
<soap11:body parts="parameters" use="literal"/>
<soap11:header message="ns0:CICSPGMOperationRequest" part="request_header" use="literal"/></wsdl:input>
<wsdl:output name="getDSUProfileResponse">
<soap11:body use="literal"/></wsdl:output></wsdl:operation></wsdl:binding>
<wsdl:service name="DSUProfileService">
<wsdl:port name="DSUProfilePort" binding="ns0:DSUProfilePortBinding">
<soap11:address location="[address]"/></wsdl:port></wsdl:service></wsdl:definitions>