<s0:definitions xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://services" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" name="MyOperationsServiceDefinitions" targetNamespace="http://services">
<s0:types>
<xs:schema xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://services" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://services">
<xs:element name="MyUpper">
<xs:complexType>
<xs:sequence>
<xs:element name="a" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="MyUpperResponse">
<xs:complexType>
<xs:sequence>
<xs:element name="return" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
</s0:types>
<s0:message name="MyUpper">
<s0:part element="s1:MyUpper" name="parameters"/>
</s0:message>
<s0:message name="MyUpperResponse">
<s0:part element="s1:MyUpperResponse" name="parameters"/>
</s0:message>
<s0:portType name="MyOperations">
<s0:operation name="MyUpper" parameterOrder="parameters">
<s0:input message="s1:MyUpper"/>
<s0:output message="s1:MyUpperResponse"/>
</s0:operation>
</s0:portType>
<s0:binding name="MyOperationsServiceSoapBinding" type="s1:MyOperations">
<s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<s0:operation name="MyUpper">
<s2:operation style="document"/>
<s0:input>
<s2:body parts="parameters" use="literal"/>
</s0:input>
<s0:output>
<s2:body parts="parameters" use="literal"/>
</s0:output>
</s0:operation>
</s0:binding>
<s0:service name="MyOperationsService">
<s0:port binding="s1:MyOperationsServiceSoapBinding" name="MyOperationsSoapPort">
<s2:address location="http://localhost:7001/MyLastWSProject/MyOperations"/>
</s0:port>
</s0:service>
</s0:definitions>
